// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pchjpplivbzpjokjbuic.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBjaGpwcGxpdmJ6cGpva2pidWljIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5OTgxMTksImV4cCI6MjA2NjU3NDExOX0.KeaBbKin-9dD1fToPkclUB7j2RYucBRTPVfHmtWVX3Y";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);